language: python
python:
    - 3.3
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install -r requirements_test.txt --use-mirrors
before_script:
    - mkdir -p docs/tests/html
script:
    - py.test tests/ --cov watson --cov-report term-missing
after_success:
    - coveralls --verbose