markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
pretty_style: html_extension
permalink: none
lsi: false
safe: false
baseurl: '/watson'
